name: Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Blog-API
      PROJECT_VERSION: "0.0.1"
      USE_SQLITE: True
      SQLITE_URL: sqlite///db.db
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run tests with coverage
        run: pytest --cov=./ --cov-report=term-missing ./app/tests