name: Ruff Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: check -- --format=github  # Note the double dash